# Generated by Django 4.2.5 on 2023-10-17 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_padre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ninoabuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField(max_length=30)),
                ('numero_identificacion', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
    ]
