# Generated by Django 4.2.5 on 2024-02-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nick',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.IntegerField(choices=[(1, 'Usuario'), (2, 'Ninos/Abuelos'), (3, 'Padres'), (4, 'Administrador')], default=1),
        ),
    ]
